services:
  garage:
    image: dxflrs/garage:b6b18427a5fc9b5b7540cf6d0843afd5cf7f9b56
    command: ['/garage', 'server']
    volumes:
      - ./config/garage.toml:/etc/garage.toml:ro
#      - garage_meta:/var/lib/garage/meta
#      - garage_data:/var/lib/garage/data
    ports:
      - "3900:3900"
      - "3903:3903"

  openbao:
    image: openbao/openbao:latest
    command: bao server -dev -dev-listen-address=0.0.0.0:8200 -dev-root-token-id=root
    environment:
      BAO_DEV_ROOT_TOKEN_ID: root
      BAO_ADDR: http://0.0.0.0:8200
    ports:
      - "8200:8200"

  controller:
    build: .
    depends_on:
      - garage
      - openbao
    environment:
      BAO_ADDR: http://openbao:8200
      BAO_TOKEN: root
      BAO_KV_MOUNT: kv
      BAO_PREFIX: garage
      GARAGE_ADMIN_URL: http://garage:3903
      GARAGE_ADMIN_TOKEN: dev-garage-admin-token
      POLL_INTERVAL_SECONDS: "10"
      RUST_LOG: info

  toolbox:
    image: alpine:3.20
    command: sh -c "sleep infinity"
    depends_on:
      - garage
      - openbao

#volumes:
#  garage_meta:
#  garage_data:
